### ISSUE TITLE
Login button doesn't respect text color

### ISSUE THREAD

**Issue by matbrady** [Log1x/modern-login#1]
## Problem
When a light background (`brand`) color is used, the login button text is difficult to read. 

### Example
Applying a palette with the follow:
```php
add_filter('login_color_palette', function () {
    return [
        'text' => '#999',
        'brand' => '#F0F0F4',
        'trim' => '#040437',
        'trim-alt' => '#fff',
    ];
});
```
will produce this result:

<img width="150" alt="Screenshot 2020-02-06 16 47 46" src="https://user-images.githubusercontent.com/1770862/73981800-0ec7ee00-4901-11ea-9a64-8a04aea2a8fa.png">

## Possible solution
Include styles so that the login button text respects the `text` palette value.

**Comment by Log1x** [comment]
hmm... perhaps I could add a setting to the filter, but also if it is not set, fall back to some kind of function that attempt to invert the color or something based on trim-alt.

**Comment by Log1x** [comment]
alright assuming it doesn't annoy anyone it should invert automagically now. :)
