### ISSUE TITLE
Login Letter/Logo Spacing on Session Expiration 

### ISSUE THREAD

**Issue by matbrady** [Log1x/modern-login#2]
## Problem
Noticed something super minor today but the login/logo letter is a little cramped when the admin session expires. This isn't apparent with the default Wordpress styles because the top modal bar is the same color as the iframed login background. By changing the background color with this package the spacing, or lack of, becomes apparent. 

### Examples
<img width="600" alt="spacing_issue" src="https://user-images.githubusercontent.com/1770862/74056692-77ba6f00-49b0-11ea-85f7-7c58a7d8a9e9.png">

![wordpress_login](https://user-images.githubusercontent.com/1770862/74056763-96b90100-49b0-11ea-85b3-3e40b866475d.gif)

### Steps to reproduce

1. Login to the admin 
1. Delete domain cookies
1. Wait for session expiration login modal to appear

## Possible Solution

padding?

**Comment by Log1x** [comment]
Unfortunately I can't do anything about the bottom padding or changing the modal header since that is outside of the iFrame, but I added padding around the main wrapper to fix the logo.
