### ISSUE TITLE
Admin password reminder not visible

### ISSUE THREAD

**Issue by matbrady** [Log1x/modern-login#4]
## Problem 

When a dark color is used for the `trim` value, the [admin password reminder](https://make.wordpress.org/core/2019/10/17/wordpress-5-3-admin-email-verification-screen/) is eligible. Some details related to the admin password reminder can be found [here](https://make.wordpress.org/core/2019/10/17/wordpress-5-3-admin-email-verification-screen/).
This error occurs with version **1.0.5**

## Example

<img width="300" src="https://user-images.githubusercontent.com/1770862/89222244-b9645500-d5a2-11ea-9ce2-ebaba8a2dfeb.png" /> <img width="320" src="https://user-images.githubusercontent.com/1770862/89222439-0d6f3980-d5a3-11ea-85c3-663bca427359.png" />

The markup for this form includes the following. This should include the class names needed to adjust the styles appropriately. 

```html
<form class="admin-email-confirm-form" name="admin-email-confirm-form"
  action="https://redacted/wp/wp-login.php?action=confirm_admin_email" method="post">
  <input type="hidden" id="confirm_admin_email_nonce" name="confirm_admin_email_nonce" value="4aa4746d3d" /><input
    type="hidden" name="_wp_http_referer"
    value="https://redacted%2Fwp%2Fwp-admin%2F&amp;action=confirm_admin_email&amp;wp_lang=en_US" />
  <input type="hidden" name="redirect_to" value="https://redacted/wp/wp-admin/" />

  <h1 class="admin-email__heading">
    Administration email verification </h1>
  <p class="admin-email__details">
    Please verify that the <strong>administration email</strong> for this website is still correct. <a
      href="https://wordpress.org/support/article/settings-general-screen/#email-address" rel="noopener noreferrer"
      target="_blank">Why is this important?<span class="screen-reader-text"> (opens in a new tab)</span></a> </p>
  <p class="admin-email__details">
    Current administration email: <strong>redacted@gmail.com</strong> </p>
  <p class="admin-email__details">
    This email may be different from your personal email address. </p>

  <div class="admin-email__actions">
    <div class="admin-email__actions-primary">
      <a class="button button-large"
        href="https://redacted/wp/wp-admin/options-general.php?highlight=confirm_admin_email">Update</a>
      <input type="submit" name="correct-admin-email" id="correct-admin-email"
        class="button button-primary button-large" value="The email is correct" />
    </div>
    <div class="admin-email__actions-secondary">
      <a
        href="https://redacted%2Fwp%2Fwp-admin%2F&#038;action=confirm_admin_email&#038;remind_me_later=c5834aa3ec">Remind
        me later</a>
    </div>
  </div>
</form>
```

## Steps to reproduce 

WordPress >=5.3 defaults to showing the reminder every 6 months when logging in to the admin. There does not appear to be a way to programmatically trigger the reminder. You can adjust the interval at which it appears with the [`admin_email_check_interval` filter](https://developer.wordpress.org/reference/hooks/admin_email_check_interval/). The best chance at getting it to appear is to log into a site that you haven't recently.

**Comment by Log1x** [comment]
Fixed along with #3
